import React, { Fragment, useEffect, useState, useRef } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Head from 'next/head';
import axios from 'axios';

export default function Crud() {
  // get data from database
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);

  const getData = () => {
    setLoading(true);
    axios.get('http://localhost:5000/api')
    .then((res) => { 
      setData(res.data)
      setLoading(false); 
    })
    .catch((err) => { 
      console.log(err) 
    })
  }

  useEffect(() => {
    getData();  
  }, []);

  return (
    <div className='bg-img'>

      <Head>
        <title>Web Dev - Web App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="https://clipground.com/images/programming-logo-clipart-5.jpg"></link>
      </Head>

      <main>
        <h3 className='font-bold mt-2 text-2xl text-blue-700 text-center'>Dashboard</h3>
        <table className='mx-auto my-2'>
          <tr className='bg-gray-100 border-2 border-gray-200'>
            <th className='border-2 border-gray-200 text-center'>Number</th>
            <th className='border-2 border-gray-200 text-center'>Title</th>
            <th className='border-2 border-gray-200 text-center'>Topic</th>
            <th className='border-2 border-gray-200 text-center'>Link</th>
            <th className='border-2 border-gray-200 text-center'>Edit</th>
            <th className='border-2 border-gray-200 text-center'>Delete</th>
          </tr>
          {loading ? (
              <Fragment>Loading...</Fragment>
            ) : (data.map((item, index) => {
            return (
              <Fragment>
                <tr className='border-2 border-gray-200'>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{index + 1}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{item.title}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{item.topic}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{item.link}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>
                    <button className='bg-blue-500 hover:bg-blue-700 font-semibold mx-1 py-1 px-2 rounded text-white'>
                      <i className="bi bi-pencil-fill"></i>
                    </button>
                  </td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>
                    <button className='bg-blue-500 hover:bg-blue-700 font-semibold mx-1 py-1 px-2 rounded text-white'>
                      <i className="bi bi-trash-fill"></i>
                    </button>
                  </td>
                </tr>
              </Fragment>
            )}))
          }
        </table>
      </main>
    </div>
  )
}
