import React, { Fragment, useEffect, useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';

export default function Crud() {
  // get data from database
  const [data, setData] = useState([]);
  const [title, setTitle] = useState('');
  const [topic, setTopic] = useState('');
  const [link, setLink] = useState('');
  const [successAddData, setSuccessAddData] = useState(false);
  const [loading, setLoading] = useState(true);
  const [setSuccessDeleteData] = useState(false);

  const getData = () => {
    setLoading(true);
    axios.get('http://localhost:5000/api')
    .then((res) => { 
      setData(res.data)
      setLoading(false); 
    })
    .catch((err) => { 
      console.log(err) 
    })
  }

  useEffect(() => {
    getData();  
  }, []);

  // add data
  const submitNewData = () => {
    axios.post('http://localhost:5000/api',{
      title,
      topic,
      link,
    })
    .then(() => {
      setSuccessAddData(true)
    })
    .catch((err) => { 
      setSuccessAddData(false) 
    })
  }

  // edit data
  const editData = () => {}
  
  // delete data
  const deleteData = () => {
    try {
      axios.delete(URL, {
        headers: {
          Authorization: authorizationToken
        },
        data: {
          source: source
        }
      })
      setSuccessDeleteData(true)
    }
    catch(err) { 
      setSuccessDeleteData(false) 
    }
  }

  return (
    <div className='opensans m-0 p-0 h-full'>

      <Head>
        <title>Dashboard - Web App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="https://clipground.com/images/programming-logo-clipart-5.jpg"></link>
      </Head>

      <nav style={{position:'fixed'}}
        className='bg-gray-100 flex justify-end py-1 pr-3 top-0 shadow-sm space-x-3 text-black w-100 z-10'
      >
        <Link href='/'>
          <a className="font-bold bg-green-300 hover:bg-green-400 no-underline my-0 px-3 py-2 rounded-lg text-white">
            Home <i class="bi bi-box-arrow-left mx-1"></i>
          </a>
        </Link>
      </nav>

      <main className='mt-20'>
        <form 
          onSubmit={submitNewData}
          className='border-2 border-blue-500 my-2 mx-auto p-3 rounded shadow w-2/5'
        >
          <h3 className='font-bold text-2xl text-blue-700 text-center'>Add or Change Data</h3>
          <hr/>
          <div className='col my-1'>
            <label className='form-label mx-auto'>Title</label>
            <input className='form-control border-2 hover:border-blue-600 mx-auto rounded'
              type='text'  
              placeholder='Input Title'
              value={title} 
              onChange={(e) => {
                setTitle(e.target.value);
                setSuccessAddData(false);
              }}
            />
          </div>
          <div className='col my-1'>
            <label className='form-label mx-auto'>Topic</label>
            <input className='form-control border-2 hover:border-blue-600 mx-auto rounded'
              type='text'
              placeholder='Input Topic'
              value={topic} 
              onChange={(e) => {
                setTopic(e.target.value);
                setSuccessAddData(false);
              }}
            />
          </div>
          <div className='col my-1'>
            <label className='form-label mx-auto'>Link</label>
            <input className='form-control border-2 hover:border-blue-600 mx-auto rounded'
              type='text'
              placeholder='Input Link'
              value={link} 
              onChange={(e) => {
                setLink(e.target.value);
                setSuccessAddData(false);
              }}
            />
          </div>    
          <div className="d-grid gap-2 mt-2">
            <button type="submit" className="btn btn-primary">Submit</button>
          </div>
          {successAddData === true (
            <div className="alert alert-primary my-1">Data berhasil di tambahkan</div>
          )}
        </form>

        <hr/>
        <h3 className='font-bold text-2xl text-blue-700 text-center'>Dashboard</h3>
        <table className='mx-auto my-2'>
          <tr className='bg-gray-100 border-2 border-gray-200'>
            <th className='border-2 border-gray-200 text-center'>id</th>
            <th className='border-2 border-gray-200 text-center'>Title</th>
            <th className='border-2 border-gray-200 text-center'>Topic</th>
            <th className='border-2 border-gray-200 text-center'>Link</th>
            <th className='border-2 border-gray-200 text-center'>Edit</th>
            <th className='border-2 border-gray-200 text-center'>Delete</th>
          </tr>
          {loading ? (
            <Fragment>Loading...</Fragment>
          ) : (data.map((item, index) => {
            return (
              <Fragment key={index}>
                <tr className='border-2 border-gray-200'>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{item.id}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{item.title}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{item.topic}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>{item.link}</td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>
                    <button onClick={editData} className='bg-green-500 hover:bg-blue-700 font-semibold mx-1 py-1 px-2 rounded text-white'>
                      <i className="bi bi-pencil-fill"></i>
                    </button>
                  </td>
                  <td className='border-2 border-gray-200 mb-1 px-1'>
                    <button onClick={deleteData} className='bg-red-500 hover:bg-blue-700 font-semibold mx-1 py-1 px-2 rounded text-white'>
                      <i className="bi bi-trash-fill"></i>
                    </button>
                  </td>
                </tr>
              </Fragment>
            )})
          )}
        </table>
      </main>
    </div>
  )
}
