import React, { useEffect, useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import '../styles/Home.module.css';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Footer from '../components/Footer';
import axios from 'axios';
import {Spinner} from 'react-bootstrap';

export default function Crud() {
  // get data from database
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);

  const getData = () => {
    setLoading(true);
    axios.get('https://express-crud-backend.herokuapp.com/api')
    .then((res) => { 
      setData(res.data)
      setLoading(false); 
    })
    .catch((err) => { 
      console.log(err) 
    })
  }

  useEffect(() => {
    getData();  
  }, []);

  return (
    <div className='bg-slate-50 opensans m-0'>

      <Head>
        <title>Web Dev</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="https://clipground.com/images/programming-logo-clipart-5.jpg"></link>
      </Head>

      <nav style={{backgroundColor:'transparent',position:'fixed'}}
        className='flex justify-center m-0 py-1 px-0 top-0 shadow-sm space-x-3 text-black w-100'
      >
        {[
          ['Home', '/'],
          ['Register', '/register'],
          ['Login','/login'],
          ['Admin','/admin'],
        ].map(([title, url, index]) => (
          <Link href={url} key={index}>
            <a className="font-bold bg-green-300 hover:bg-green-400 no-underline my-0 px-3 py-2 rounded-lg text-white">
              {title}
            </a>
          </Link>
        ))}
      </nav>

      <main className='p-0 m-0'>
        <img src="/wallpaper.jpg" alt="coding" width='100%' height='100%' 
          className=''
        />
    
        <div className='mb-4' className='' style={{marginTop: '-50%'}}>
          <div className='mx-auto mb-5 p-0 space-y-1 md:space-y-3 lg:space-y-4 text-left w-11/12 md:w-5/6 lg:w-4/6 text-white'>
            <h3 className='font-bold text-xl md:text-3xl lg:text-5xl underline'>
              Express Basic, CRUD and Auth
            </h3>
            <p>Compilation of Express.js Back End (Node.js) Learning Sources</p>
            <p>by M. Rafli Ramadhan</p>
          </div>
          <div
            className='my-3 mx-auto w-11/12 md:w-5/6 lg:w-4/6'
          >
            {loading ? (
              <p className='font-bold p-2 shadow text-center text-xl text-white'>
                <Spinner animation="border" variant="info" /> Loading...
              </p>
              ) : (data.map((item, index) => {
                return (
                  <div className='card my-2'>
                    <a key={index} href={item.link} 
                      className='no-underline' 
                      target='_blank' 
                      rel='noreferrer'
                    >
                      <p className='bg-slate-400 hover:bg-green-500 border m-0 p-2 rounded shadow text-left text-white'>
                        {item.title}
                      </p>
                    </a>
                  </div>
                )
              }))
            }
          </div>
        </div>

        <hr/>
        <Footer/>
      </main>
    </div>
  )
}