import React, { useEffect, useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import '../styles/Home.module.css';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Footer from '../components/Footer';
import axios from 'axios';
import {Accordion} from 'react-bootstrap';

export default function Crud() {
  // get data from database
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);

  const getData = () => {
    setLoading(true);
    axios.get('https://express-crud-backend.herokuapp.com/api')
    .then((res) => { 
      setData(res.data)
      setLoading(false); 
    })
    .catch((err) => { 
      console.log(err) 
    })
  }

  useEffect(() => {
    getData();  
  }, []);

  return (
    <div className='bg-slate-50 opensans m-0'>

      <Head>
        <title>Web Dev - Web App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" href="https://clipground.com/images/programming-logo-clipart-5.jpg"></link>
      </Head>

      <nav style={{backgroundColor:'transparent',position:'fixed'}}
        className='flex justify-center m-0 py-1 px-0 top-0 shadow-sm space-x-3 text-black w-100 z-10'
      >
        {[
          ['Home', '/',1],
          ['Admin','/login',2],
          ['Register', '/register',3],
        ].map(([title, url, id]) => (
          <Link href={url} key={id}>
            <a className="font-bold bg-green-300 hover:bg-green-400 no-underline my-0 px-3 py-2 rounded-lg text-white">
              {title}
            </a>
          </Link>
        ))}
      </nav>

      <main className='pt-0 mt-0'>
        <img src="/wallpaper.jpg" alt="coding" width='100%' height='100%' />
        <div className='mb-4'>
          <div className='mx-auto mb-5 p-0 space-y-1 md:space-y-3 lg:space-y-4 text-left w-11/12 lg:w-4/5 text-white' style={{'margin-top':'-50%'}}>
            <h3 className='font-bold mt-2 text-xl md:text-3xl lg:text-5xl underline'>Learning Path Web Dev</h3>
            <p className=''>Compilation of Web Programming Back End (Node.js) Learning Sources</p>
            <p className=''>by M. Rafli Ramadhan</p>
          </div>
          <Accordion defaultActiveKey="0" className='bg-slate-50 justify-center mt-1 mb-3 mx-auto w-11/12 lg:w-5/6'>
            {loading ? (
              <p className='bg-white font-bold p-2 text-center text-xl shadow'>Loading...</p>
              ) : (data.map((item, index) => {
                return (
                  <Accordion.Item eventKey={index} className='my-2 shadow' key={index}>
                    <Accordion.Header>
                      <p className='font-bold my-0 hover:text-cyan-700'>{item.title} : {item.link}</p>
                    </Accordion.Header>
                    <Accordion.Body className='p-0'>
                      <iframe src={item.link}
                        style={{width: '100%',height: '1100px'}}
                      ></iframe>
                    </Accordion.Body>
                  </Accordion.Item>
                )
              }))
            }
          </Accordion>
        </div>
      </main>
      <hr/>
      <Footer/>

    </div>
  )
}